# Generated by Django 6.0.3 on 2026-07-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0004_customerchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
    ]
